version: '2.5'

services:
  quantumsitefinitysql:
    hostname: quantumsitefinitysql
    container_name: quantumsitefinitysql
    environment:
      - SA_PASSWORD=Sitefinity14@2022
      - ACCEPT_EULA=Y      
      - MSSQL_PID=Express
    ports:
      - "5400:1433"
    volumes:
      - ./data/sql_data/data:/var/opt/mssql/data
      - ./data/sql_data/backup:/var/opt/mssql/backup

  quantumsitefinitywebapp:
    hostname: cms.quantum.local
    container_name: quantumsitefinitywebapp
    ports:
      - "4020:4020"
      - "4021:4021"
      - "8085:80"
      - "8086:443"
    volumes:
      - ./data/app_data:C:/inetpub/wwwroot/App_Data 
   
  quantumsitefinityrenderer:
    hostname: www.quantum.local
    container_name: quantumsitefinityrenderer
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_HTTPS_PORT=5001
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      #- ${APPDATA}\microsoft\UserSecrets\:C:\Users\ContainerUser\AppData\Roaming\microsoft\UserSecrets
      - ./data/https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https
      